kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: coppa-clusterrole
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["", "networking.istio.io"]
    resources:
      - namespaces
      - configmaps
      - services
      - virtualservices
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
