kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: coppa-clusterrolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: Group
    name: system:serviceaccounts:{{ .Release.Namespace }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: coppa-clusterrole
  apiGroup: rbac.authorization.k8s.io
