kind: ConfigMap
apiVersion: v1
metadata:
  name: coppa-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: coppa
    version: {{ .Values.stage }}
data:
  ENVIRONMENT: {{ .Values.env }}
  HOST: {{ .Values.host }}
  DOMAIN: {{ .Values.domain }}
  STAGE: {{ .Values.stage }}
  GCLOUD_PROJECT_ID: {{ .Values.gcloudProjectId }}
