apiVersion: v1
kind: Secret
metadata:
  name: coppa-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  CLOUDFLARE_API_EMAIL: {{ .Values.cloudflareApiEmail | b64enc }}
  CLOUDFLARE_API_KEY: {{ .Values.cloudflareApiKey | b64enc }}
  GITHUB_WEBHOOK_SECRET: {{ .Values.githubWebhookSecret | b64enc }}
  NEW_RELIC_API_KEY: {{ .Values.newrelicApiKey | b64enc }}
  # already Base64'd in CircleCI
  GCLOUD_SERVICE_KEY: {{ .Values.gcloudServiceKey }}
